// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClauaxiGbaw-MuwIPwqjyC7kMPSSOWYTA',
    appId: '1:1018557691786:web:c160af0bdec872e6fc7a73',
    messagingSenderId: '1018557691786',
    projectId: 'bee-mvp-3ab43',
    authDomain: 'bee-mvp-3ab43.firebaseapp.com',
    storageBucket: 'bee-mvp-3ab43.firebasestorage.app',
    measurementId: 'G-D4KR8B8WS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2s6-L1snukKJxFeuVga6IVNtBh1I-uEs',
    appId: '1:1018557691786:android:c3a9d0f03ba947f4fc7a73',
    messagingSenderId: '1018557691786',
    projectId: 'bee-mvp-3ab43',
    storageBucket: 'bee-mvp-3ab43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMFySj3BKPD_VXJv0yLMrkV-r0wtnwFA',
    appId: '1:1018557691786:ios:e9e29feb7e046a78fc7a73',
    messagingSenderId: '1018557691786',
    projectId: 'bee-mvp-3ab43',
    storageBucket: 'bee-mvp-3ab43.firebasestorage.app',
    iosBundleId: 'com.momentumhealth.beemvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgMFySj3BKPD_VXJv0yLMrkV-r0wtnwFA',
    appId: '1:1018557691786:ios:e6a07d9959574bc6fc7a73',
    messagingSenderId: '1018557691786',
    projectId: 'bee-mvp-3ab43',
    storageBucket: 'bee-mvp-3ab43.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClauaxiGbaw-MuwIPwqjyC7kMPSSOWYTA',
    appId: '1:1018557691786:web:34cf5220832f7975fc7a73',
    messagingSenderId: '1018557691786',
    projectId: 'bee-mvp-3ab43',
    authDomain: 'bee-mvp-3ab43.firebaseapp.com',
    storageBucket: 'bee-mvp-3ab43.firebasestorage.app',
    measurementId: 'G-FT2XKR931C',
  );
}
