version: '3.9'

services:
  db-test:
    image: postgres:14
    container_name: db-test
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - ./docker/postgres-test/init:/docker-entrypoint-initdb.d:ro 