#!/usr/bin/env bash
# dev_kickoff.sh – non-interactive helper for Developer Kick-Off Playbook
# Usage: ./scripts/dev_kickoff.sh M1.12.1
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <milestone-code>" >&2
  exit 1
fi
MILESTONE=$1
BRANCH="feature/${MILESTONE}"

# Ensure clean tree
if [[ -n $(git status --porcelain) ]]; then
  echo "❌ Working tree dirty. Commit or stash changes first." >&2
  exit 1
fi

echo "🔄 Creating branch $BRANCH from main…"
git checkout main >/dev/null
git pull --ff-only

git checkout -b "$BRANCH"

echo "✅ Branch $BRANCH created. Pushing & opening draft PR…"
git push -u origin "$BRANCH"
# Requires GitHub CLI authenticated
if command -v gh >/dev/null; then
  gh pr create --title "WIP: $MILESTONE" --base main --head "$BRANCH" --draft --body "Tracking PR for $MILESTONE milestone. Auto-generated by dev_kickoff.sh." || true
fi

echo "🏁 Kick-off complete. Happy coding!" 