openapi: 3.1.0
info:
  title: Suggest Action Steps API
  version: 0.1.0

paths:
  /suggest_action_steps:
    post:
      summary: Generate action step suggestions for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  format: uuid
              required:
                - user_id
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ActionStep"
        "400":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "429":
          description: Rate Limited
          headers:
            Retry-After:
              schema:
                type: integer
                format: int32
                example: 30
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /health:
    get:
      summary: Health check endpoint
      responses:
        "200":
          description: OK

components:
  schemas:
    ActionStep:
      type: object
      properties:
        category:
          type: string
        description:
          type: string
        frequency:
          type: integer
          minimum: 3
          maximum: 7
        week_start:
          type: string
          format: date
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        correlation_id:
          type: string
