openapi: 3.1.0
info:
  title: Suggest Action Steps API
  version: 1.0.0
paths:
  /suggest-action-steps:
    post:
      summary: Get suggested action steps for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: Unique user identifier
              required:
                - user_id
      responses:
        "200":
          description: Suggestions payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  suggestions:
                    type: array
                    items:
                      $ref: "#/components/schemas/ActionStepSuggestion"
        "429":
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RateLimitedError"
components:
  schemas:
    ActionStepSuggestion:
      type: object
      properties:
        id:
          type: string
          description: Unique suggestion key
        title:
          type: string
        category:
          type: string
        description:
          type: string
      required:
        - id
        - title
        - category
        - description
    RateLimitedError:
      type: object
      properties:
        code:
          type: string
          enum: [RATE_LIMITED]
        message:
          type: string
        retry_after:
          type: integer
