openapi: 3.0.3
info:
  title: BEE-MVP Wearable API
  version: "1.0.0"
  description: |
    Version **v1** of the BEE-MVP wearable data API exposed via Supabase Edge Functions.
    All endpoints require the `X-Api-Version: 1` header and Bearer authorization (Supabase JWT).

    Example cURL (Daily Sleep Score):
    ```bash
    curl -H "Authorization: Bearer <your_jwt>" \
         -H "X-Api-Version: 1" \
         "https://<project>.functions.supabase.co/wearable-summary-api/v1/daily-sleep-score?user_id=123&date=2025-06-01"
    ```
servers:
  - url: https://<project>.functions.supabase.co
paths:
  /wearable-summary-api/v1/ping:
    get:
      summary: Health check.
      responses:
        "200":
          description: Service operational.
  /wearable-summary-api/v1/daily-sleep-score:
    get:
      summary: Returns crude sleep quality score (0-100) for given day.
      parameters:
        - name: user_id
          in: query
          required: true
          schema: { type: string }
        - name: date
          in: query
          required: true
          description: YYYY-MM-DD date string.
          schema: { type: string, format: date }
      responses:
        "200":
          description: Sleep score payload.
  /wearable-summary-api/v1/rolling-hr:
    get:
      summary: Returns average heart-rate in the last *n* minutes.
      parameters:
        - { name: user_id, in: query, required: true, schema: { type: string } }
        - {
            name: minutes,
            in: query,
            required: false,
            schema: { type: integer, default: 60 },
          }
      responses:
        "200":
          description: Average heart-rate.
  /wearable-summary-api/v1/history:
    get:
      summary: Returns raw data points for the requested time range.
      parameters:
        - { name: user_id, in: query, required: true, schema: { type: string } }
        - {
            name: data_type,
            in: query,
            required: true,
            schema: {
              type: string,
              enum: [heart_rate, sleep_minutes, steps, hrv],
            },
          }
        - {
            name: start,
            in: query,
            required: true,
            schema: { type: string, format: date-time },
          }
        - {
            name: end,
            in: query,
            required: true,
            schema: { type: string, format: date-time },
          }
      responses:
        "200": { description: List of samples. }
  /wearable-summary-api/v1/trend:
    get:
      summary: Returns aggregated trend buckets (day/week/month).
      parameters:
        - { name: user_id, in: query, required: true, schema: { type: string } }
        - {
            name: data_type,
            in: query,
            required: true,
            schema: { type: string },
          }
        - {
            name: bucket,
            in: query,
            required: false,
            schema: { type: string, default: day, enum: [day, week, month] },
          }
        - {
            name: range,
            in: query,
            required: false,
            schema: { type: string, default: "30" },
          }
      responses:
        "200": { description: Aggregated trend rows. }
  /wearable-data-export/v1:
    get:
      summary: Exports CSV dataset for the requested time range.
      parameters:
        - {
            name: start_date,
            in: query,
            required: false,
            schema: { type: string, format: date },
          }
        - {
            name: end_date,
            in: query,
            required: false,
            schema: { type: string, format: date },
          }
        - {
            name: user_id,
            in: query,
            required: false,
            schema: { type: string },
          }
      responses:
        "200":
          description: CSV file download.
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
