-- Migration: create analytics_events table for MVP telemetry
-- Adjust timestamp in filename as needed by Supabase CLI

-- 1. Create table -----------------------------------------------------------
create table if not exists public.analytics_events (
    id          bigint generated by default as identity primary key,
    event_name  text        not null,
    params      jsonb       not null default '{}'::jsonb,
    created_at  timestamptz not null default now(),
    user_id     uuid references auth.users(id) on delete set null
);

comment on table public.analytics_events is 'Lightweight UX analytics captured from the mobile app during MVP.';

-- 2. Row-Level Security -----------------------------------------------------
alter table public.analytics_events enable row level security;

-- Allow any authenticated user to insert their own event row ----------------
create policy "analytics_events_insert" on public.analytics_events
  for insert with check (auth.uid() = user_id or user_id is null);

-- Optional: allow service role / edge functions full access -----------------
-- (Supabase service_role bypasses RLS by default.)

-- 3. Indexes ----------------------------------------------------------------
create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

-- 4. Grant read access to admin dashboards ---------------------------------
grant select on public.analytics_events to anon, authenticated; 