name: Deploy Suggest Action Steps Edge Function

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/suggest_action_steps/**'
      - '.github/workflows/deploy_suggest_action_steps.yml'

jobs:
  deploy_suggest_action_steps:
    runs-on: ubuntu-latest
    container: ghcr.io/gmtfrombc/ci-base:2025-07-12
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.46.3

      - name: Install Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/download/v1.154.1/supabase_1.154.1_linux_amd64.deb -o supabase.deb
          sudo dpkg -i supabase.deb
          supabase --version

      - name: Deploy suggest_action_steps edge function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase login --token $SUPABASE_ACCESS_TOKEN --no-browser || true
          supabase functions deploy suggest_action_steps --project-ref $SUPABASE_PROJECT_ID --no-verify-jwt --debug 