name: Deploy suggest-action-steps Edge Function

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/suggest-action-steps/**'
      - '.github/workflows/deploy_suggest_action_steps.yml'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          supabase functions deploy suggest-action-steps \
            --project-ref $SUPABASE_PROJECT_REF \
            --no-verify-jwt
