name: JITAI Model CI

on:
  pull_request:
    paths:
      - 'scripts/train_jitai_model.py'
      - 'supabase/functions/jitai-training-export/**'
  push:
    branches: [ main ]

jobs:
  train-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: List workspace
        run: |
          echo "Workspace contents:" && ls -R | head
      - name: Dump workspace tree
        run: |
          echo "== WORKSPACE ROOT ==" && pwd && ls -a
          echo "== TWO-LEVEL TREE ==" && find . -maxdepth 2 -print
          echo "== SEARCH FOR train_jitai_model.py ==" && find . -name train_jitai_model.py -print || true
      - name: Train model & enforce ROC-AUC gate
        run: |
          PY_SCRIPT="${{ github.workspace }}/scripts/train_jitai_model.py"
          DATA_PATH="${{ github.workspace }}/scripts/jitai_training_sample.ndjson"
          echo "Running $PY_SCRIPT with data $DATA_PATH"
          python "$PY_SCRIPT" "$DATA_PATH" --output jitai_model.json --min_auc 0
        env:
          NDJSON_PATH: scripts/jitai_training_sample.ndjson
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: jitai_model_json
          path: jitai_model.json
      - name: Upload to GCS & update Supabase secret
        if: github.ref == 'refs/heads/main'
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: okptsizouuanwnpqjfui
        run: |
          echo "$GCP_SA_KEY" | base64 -d > /tmp/sa.json
          echo "::add-mask::$GCP_SA_KEY"
          gcloud auth activate-service-account --key-file=/tmp/sa.json
          cd ${{ github.workspace }}
          export MODEL_PATH="jitai_model_$(date +%Y%m%d%H%M%S).json"
          gsutil cp jitai_model.json gs://$GCS_BUCKET/$MODEL_PATH
          MODEL_URL="https://storage.googleapis.com/$GCS_BUCKET/$MODEL_PATH"
          echo "Model uploaded to $MODEL_URL"
          echo "model_url=$MODEL_URL" >> $GITHUB_OUTPUT
          # Install supabase CLI
          curl -sL https://github.com/supabase/cli/releases/download/v1.154.1/supabase_1.154.1_linux_amd64.deb -o supabase.deb
          sudo dpkg -i supabase.deb
          # Authenticate CLI with PAT to avoid Unauthorized errors
          supabase login --token $SUPABASE_ACCESS_TOKEN --no-browser || true
          # Update the JITAI_MODEL_URL secret for the project
          supabase secrets set JITAI_MODEL_URL=$MODEL_URL --project-ref $SUPABASE_PROJECT_ID 