name: JITAI Model CI

on:
  pull_request:
    paths:
      - 'scripts/train_jitai_model.py'
      - 'supabase/functions/jitai-training-export/**'
  push:
    branches: [ main ]

jobs:
  train-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model & enforce ROC-AUC gate
        env:
          NDJSON_PATH: scripts/jitai_training_sample.ndjson
        run: |
          python scripts/train_jitai_model.py $NDJSON_PATH --output jitai_model.json
      - name: Upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: jitai_model_json
          path: jitai_model.json
      - name: Upload to GCS & update Supabase secret
        if: github.ref == 'refs/heads/main'
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCS_BUCKET: ${{ secrets.GCS_MODEL_BUCKET }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: okptsizouuanwnpqjfui
        run: |
          echo "$GCP_SA_KEY" | base64 -d > /tmp/sa.json
          echo "::add-mask::$GCP_SA_KEY"
          gcloud auth activate-service-account --key-file=/tmp/sa.json
          export MODEL_PATH="jitai_model_$(date +%Y%m%d%H%M%S).json"
          gsutil cp jitai_model.json gs://$GCS_BUCKET/$MODEL_PATH
          MODEL_URL="https://storage.googleapis.com/$GCS_BUCKET/$MODEL_PATH"
          echo "Model uploaded to $MODEL_URL"
          echo "::set-output name=model_url::$MODEL_URL"
          # Install supabase CLI
          curl -sL https://github.com/supabase/cli/releases/download/v1.154.1/supabase_1.154.1_linux_amd64.deb -o supabase.deb
          sudo dpkg -i supabase.deb
          supabase functions secrets set JITAI_MODEL_URL=$MODEL_URL --project-ref $SUPABASE_PROJECT_ID --apikey $SUPABASE_ACCESS_TOKEN 