name: Update Supabase Baseline Schema

on:
  schedule:
    # Quarterly at midnight UTC on the first of Jan/Apr/Jul/Oct
    - cron: '0 0 1 1,4,7,10 *'
  workflow_dispatch: {}

jobs:
  dump-and-pr:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: npm install -g supabase@latest

      - name: Dump current schema (without data)
        run: |
          ts=$(date +"%Y%m%d%H%M%S")
          out="supabase/baseline/${ts}_baseline_schema.sql"
          supabase db dump --db-url "$SUPABASE_DB_URL" --schema public,auth --without-data > "$out"
          echo "BASELINE_FILE=$out" >> "$GITHUB_ENV"

      - name: Commit baseline dump
        run: |
          git config --global user.email "bot@users.noreply.github.com"
          git config --global user.name "baseline-bot"
          git checkout -b chore/update-baseline-$GITHUB_RUN_ID
          git add "$BASELINE_FILE"
          git commit -m "chore: add new supabase baseline schema $BASELINE_FILE"

      - name: Push branch
        run: |
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ env.GH_TOKEN }}
          title: "chore: refresh Supabase baseline schema"
          commit-message: "chore: add new baseline schema"
          body: |
            Automated baseline schema snapshot generated by GitHub Action.
            Merges newest production schema so CI can skip legacy migrations.
          branch: pr/baseline-${{ github.run_id }} 